AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - redfish_client.gemspec
    - Gemfile
    - Rakefile
    - bin/**

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MethodMissing:
  Exclude:
    - lib/redfish_client/resource.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
